<?php
//
// File generated by ... on the 2026-02-10T20:37:29+0000
// Please do not edit manually
//

/**
 * Classes and menus for itop-synchro-dashboard (version 1.2.2)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

//
// Menus
//
class MenuCreation_itop_synchro_dashboard extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['ConfigurationTools'] = new MenuGroup('ConfigurationTools', 90, 'fas fa-cog' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['DataSourcesDashboard'] = new WebPageMenuNode('DataSourcesDashboard', utils::GetAbsoluteUrlAppRoot()."pages/exec.php?exec_module=itop-synchro-dashboard&exec_page=dashboard.php&c[menu]=DataSourcesDashboard", $__comp_menus__['ConfigurationTools']->GetIndex(), 25 , 'SynchroDataSource', UR_ACTION_READ, UR_ALLOWED_YES, null);
	}
} // class MenuCreation_itop_synchro_dashboard
