<?php
/**
 * Localized data
 *
 * @copyright Copyright (C) 2010-2024 Combodo SAS
 * @license    https://opensource.org/licenses/AGPL-3.0
 * 
 */
/**
 *
 */
Dict::Add('DE DE', 'German', 'Deutsch', [
	'Class:Template' => 'Vorlage',
	'Class:Template+' => 'Vorlage für Zusatzfelder',
	'Class:Template/Attribute:description' => 'Beschreibung',
	'Class:Template/Attribute:description+' => '',
	'Class:Template/Attribute:field_list' => 'Felder',
	'Class:Template/Attribute:field_list+' => '',
	'Class:Template/Attribute:label' => 'Label',
	'Class:Template/Attribute:label+' => 'Das Label wird als Feldbezeichner im Formular angezeigt.',
	'Class:Template/Attribute:name' => 'Name',
	'Class:Template/Attribute:name+' => 'Interner Name für ein Feld. Wird dem Endbenutzer nicht angezeigt.',
	'Class:TemplateField' => 'Feld',
	'Class:TemplateField+' => '',
	'Class:TemplateField/Attribute:code' => 'Code',
	'Class:TemplateField/Attribute:code+' => 'Attribute-Code oder beliebiger Wert',
	'Class:TemplateField/Attribute:display_condition' => 'Anzeigebedingung',
	'Class:TemplateField/Attribute:display_condition+' => 'Syntax lautet wie folgt: template->code=\'value\'   Zum Beispiel :template->PC=\'Yes\'',
	'Class:TemplateField/Attribute:format' => 'Format',
	'Class:TemplateField/Attribute:format+' => 'Regulärer Ausdruck',
	'Class:TemplateField/Attribute:initial_value' => 'Initialer Wert',
	'Class:TemplateField/Attribute:initial_value+' => '',
	'Class:TemplateField/Attribute:input_type' => 'Feldtyp',
	'Class:TemplateField/Attribute:input_type+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date' => 'Datum',
	'Class:TemplateField/Attribute:input_type/Value:date+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time' => 'Datum und Uhrzeit',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time+' => '',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list' => 'Drop-Down Liste',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list+' => '',
	'Class:TemplateField/Attribute:input_type/Value:duration' => 'Dauer',
	'Class:TemplateField/Attribute:input_type/Value:duration+' => '',
	'Class:TemplateField/Attribute:input_type/Value:hidden' => 'Versteckt',
	'Class:TemplateField/Attribute:input_type/Value:hidden+' => '',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons' => 'Liste',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons+' => '',
	'Class:TemplateField/Attribute:input_type/Value:read_only' => 'Read-Only',
	'Class:TemplateField/Attribute:input_type/Value:read_only+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text' => 'Textzeile',
	'Class:TemplateField/Attribute:input_type/Value:text+' => 'Einzeiliges Freitextfeld',
	'Class:TemplateField/Attribute:input_type/Value:text_area' => 'Textfeld',
	'Class:TemplateField/Attribute:input_type/Value:text_area+' => 'Mehrzeiliges Freitextfeld',
	'Class:TemplateField/Attribute:label' => 'Label',
	'Class:TemplateField/Attribute:label+' => 'Das Label wird als Feldbezeichner im Formular angezeigt.',
	'Class:TemplateField/Attribute:mandatory' => 'Pflichtfeld',
	'Class:TemplateField/Attribute:mandatory+' => '',
	'Class:TemplateField/Attribute:max_combo_length' => 'Schwellenwert Autovervollständigung',
	'Class:TemplateField/Attribute:max_combo_length+' => 'Liste und Drop-Down Liste: Anzahl an möglichen Werteausprägungen bis zu der eine Liste angeboten wird. Sind mehr Werte vorhanden wird eine Autovervollständigung genutzt.',
	'Class:TemplateField/Attribute:order' => 'Position',
	'Class:TemplateField/Attribute:order+' => 'Legt die Reihenfolge der Felder im Formular fest.',
	'Class:TemplateField/Attribute:template_id' => 'Vorlage',
	'Class:TemplateField/Attribute:template_id+' => '',
	'Class:TemplateField/Attribute:template_id_finalclass_recall' => 'Typ',
	'Class:TemplateField/Attribute:template_id_finalclass_recall+' => '',
	'Class:TemplateField/Attribute:values' => 'Werte (OQL oder CSV)',
	'Class:TemplateField/Attribute:values+' => '"SELECT myClass WHERE name LIKE \'foo\'" or "val1,val2,..."',
	'Class:TemplateField/Error:InvalidDisplayConditionCode' => 'Die Anzeigebedingung kann nicht den Feldcode als Quelle verwenden!',
	'Class:TemplateField/Error:InvalidDisplayConditionOql' => ' Die Anzeigebedingung hat ein falsches Format. Es sollte OQL-Bedingungen entsprechen!',
	'Menu:Templates' => 'Vorlagen',
	'Menu:Templates+' => 'Vorlagen für Zusatzfelder',
	'Templates:Need' => 'Bedarf',
	'Templates:PreviewTab:FormFields' => '',
	'Templates:PreviewTab:HiddenFields' => 'Versteckte Felder',
	'Templates:PreviewTab:Title' => 'Vorschau',
	'Templates:UserData' => 'Zusätzliche Daten',
]);
